# Generated by Django 5.2 on 2025-05-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_solicitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntoreclamacao',
            options={'verbose_name': 'Assunto da Reclamação', 'verbose_name_plural': '3- Assuntos da Reclamação'},
        ),
        migrations.AlterModelOptions(
            name='secretariaemail',
            options={'verbose_name': 'Email da Secretaria', 'verbose_name_plural': '2- Emails das Secretarias'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Solicitação', 'verbose_name_plural': '4- Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='statussolicitacao',
            options={'ordering': ['nome'], 'verbose_name': 'Status da Solicitação', 'verbose_name_plural': '1- Status das Solicitações'},
        ),
    ]
