# Generated by Django 5.2.1 on 2025-05-22 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_assuntoreclamacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lixo', 'Acúmulo de Lixo'), ('alagamento', 'Ponto de Alagamento'), ('sinalizacao', 'Falha de Sinalização'), ('buraco', 'Buraco na Via'), ('congestionamento', 'Congestionamento Frequente'), ('deslizamento', 'Risco de Deslizamento'), ('esgoto', 'Esgoto a Céu Aberto'), ('iluminacao', 'Iluminação Pública Deficiente'), ('violencia', 'Local com Ocorrência de Violência'), ('outros', 'Outros Problemas')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tipo_problema', models.CharField(choices=[('lixo', 'Acúmulo de Lixo'), ('alagamento', 'Ponto de Alagamento'), ('sinalizacao', 'Falha de Sinalização'), ('buraco', 'Buraco na Via'), ('congestionamento', 'Congestionamento Frequente'), ('deslizamento', 'Risco de Deslizamento'), ('esgoto', 'Esgoto a Céu Aberto'), ('iluminacao', 'Iluminação Pública Deficiente'), ('violencia', 'Local com Ocorrência de Violência'), ('outros', 'Outros Problemas')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('endereco_texto', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('data_reporte', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problema Urbano',
                'verbose_name_plural': '5- Problemas Urbanos',
                'ordering': ['-data_reporte'],
            },
        ),
    ]
