# Generated by Django 5.2.1 on 2025-05-22 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('lixo', 'Acúmulo de lixo'), ('alagamento', 'Alagamento'), ('sinalizacao', 'Problema de Sinalização'), ('buraco', 'Buraco na Via'), ('congestionamento', 'Congestionamento/Trânsito'), ('deslizamento', 'Risco de Deslizamento'), ('esgoto', 'Esgoto a Céu Aberto'), ('iluminacao', 'Falha na Iluminação Pública'), ('violencia', 'Local com Ocorrência de Violência'), ('outros', 'Outros Problemas')], default='outros', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco_texto', models.CharField(blank=True, help_text='Endereço aproximado do problema.', max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('em_andamento', 'Em Andamento'), ('solucionado', 'Solucionado'), ('recusado', 'Recusado/Inválido')], default='pendente', max_length=20)),
                ('data_reporte', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problema Reportado',
                'verbose_name_plural': 'Problemas Reportados',
                'ordering': ['-data_reporte'],
            },
        ),
    ]
