# Generated by Django 5.2.1 on 2025-05-22 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problema',
            options={},
        ),
        migrations.AlterField(
            model_name='problema',
            name='data_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='problema',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='problema',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
